<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Azure on Loving life and dreams.</title><link>/en/categories/azure/</link><description>Recent content in Azure on Loving life and dreams.</description><generator>Hugo -- gohugo.io</generator><language>zh-CN</language><lastBuildDate>Thu, 17 Aug 2017 18:20:18 +0000</lastBuildDate><atom:link href="/en/categories/azure/index.xml" rel="self" type="application/rss+xml"/><item><title>pymsql connects to the MSSQL database of the azure cloud</title><link>/en/2017/08/17/pymssql-azure-mssql-datasource-connect.html</link><pubDate>Thu, 17 Aug 2017 18:20:18 +0000</pubDate><guid>/en/2017/08/17/pymssql-azure-mssql-datasource-connect.html</guid><description>&lt;p>Code good code in the test environment to do a good job of testing, full of confidence to the operation of the online to the production environment, the result is a bunch of exceptions, specifically looked at the problem found to be connected to the database, abnormal information is as follows:&lt;/p>
&lt;div class="highlight">&lt;pre style="background-color:#f8f8f8;-moz-tab-size:4;-o-tab-size:4;tab-size:4">&lt;code class="language-fallback" data-lang="fallback">(40532, &amp;#39;Cannot open server &amp;#34;1433D&amp;#34; requested by the login.
The login failed. DB-Lib error message 20018, severity 20:\n
General SQL Server error: Check messages from the SQL Server\n
DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed\n&amp;#39;)
&lt;/code>&lt;/pre>&lt;/div></description></item></channel></rss>